### ISSUE TITLE
Connect 2.0 compatibility

### ISSUE THREAD

**Issue by ammmir** [ammmir/node-oauth2-provider#12]
It should be fairly trivial to add support, since we don't really use the router's regex magic.

**Comment by digitalrinaldo** [comment]
I am interested in helping with this. When I tried to get it working using simple.js, I get an error about the router.  Shouldn't the connect in express be used?

─┬ express@2.5.8 
│ ├─┬ connect@1.8.5 
│ │ └── formidable@1.0.9 
│ ├── mime@1.2.4 
│ ├── mkdirp@0.3.0 
│ └── qs@0.4.2 
├─┬ jade@0.21.0 
│ ├── commander@0.5.2 
│ └── mkdirp@0.3.0 
├─┬ oauth2-provider@1.0.1 
│ ├─┬ connect@1.8.5 
│ │ ├── formidable@1.0.9 
│ │ ├── mime@1.2.5 
│ │ └── qs@0.4.2 
│ └── serializer@0.0.3 
└── serializer@0.0.3
