### ISSUE TITLE
Create Access Token without grant

### ISSUE THREAD

**Issue by ArcoMul** [ammmir/node-oauth2-provider#28]
Hello,

I'm not an OATH (2) expert, so I may be completely wrong.
When using your module I encountered the situation that I wanted to return an access token without first getting the permission of the user.

So by sending the client secret + username + password I immediately return an access token since it is a trusted client.

Is it an idea to add this option to the module?

**Comment by ammmir** [comment]
yes, this is sometimes known as xAuth, whereby you exchange credentials for a long-lived access token.

**Comment by ammmir** [comment]
@ArcoMul can you test this out and let me know if it works for you?

**Comment by ArcoMul** [comment]
Yes, this works fine for me :-) And apparently I was talking about xAuth yes, thanks for the right term
