### ISSUE TITLE
encrypted token

### ISSUE THREAD

**Issue by tj** [ammmir/node-oauth2-provider#34]
just curious why all the encryption stuff vs just using crypto for a random access token? Also is there a way to make the token shorter?

**Comment by tj** [comment]
oh I see it's unpacked later. In the interest of having a smaller token would you mind support for saving that auxiliary data to a db?

**Comment by ammmir** [comment]
hey TJ, when i initially wrote this, i didn't want to hit the db on every request, so i opted to to embed any needed data (eg. user id, generation time) in the token itself. to protect the data, it's encrypted and signed to prevent tampering (node-serializer).

the obvious disadvantage is that you get absurdly long tokens when you're embedding even a trivial amount of data. so you're absolutely right, we need a new event.. something like this:

``` js
myOAP.on('need_access_token', function(user_id, client_id, extra_data, token_options, next) {
  // generate token and save it somewhere
  next(null, 'a-shorter-token-yo');
});
```

and then a custom token querying event:

``` js
myOAP.on('lookup_access_token', function(token, next) {
  // query data store for token
  // ...
  next(null, user_id, client_id, extra_data, grant_date);
});
```

all those args!! but i think you get the idea. basically,  if the `options` object passed to the OAuth2Provider constructor doesn't contain `crypt_key` or `sign_key` then we can bypass the embedded token method and emit these two events to allow full customization of how tokens are generated and checked.

well, that's one way to do it.. let me know if you have other ideas or want to send a pull request :D

**Comment by tj** [comment]
The main problem for me is this token gets decrypted so we can't check if it's been deauthorized, just expired (not sure how anyone else is dealing with this). I'm going to inline this lib in our app, if the changes end up being decent I'll send over a PR

**Comment by ammmir** [comment]
ah, yes, the way to handle that now is to store an id of some kind in the extra data (ie. what you pass to the callback in the `create_access_token` event). then when you get an `access_token` event, extract the id (`token.extra_data`) and look it up in your db to get the revocation status.

it should be built in to the library, though.. PR or bits of code definitely welcome, as i'll be refactoring a bunch of stuff for 2.x anyway.

**Comment by tj** [comment]
cool cool, inlined the rewrite for now but I'll try and polish it up in the near future
