### ISSUE TITLE
Express Provider

### ISSUE THREAD

**Issue by cj** [ammmir/node-oauth2-provider#4]
Hi,

Would it be possible to get an example of creating a provider (server) with express?

Many thanks,

CJ

**Comment by ammmir** [comment]
express uses connect underneath, so you should be able to use it like any other middleware:

```
var app = require('express').createServer({...});
var myOAP = new OAuth2Provider(...);
// set up myOAP

app.configure(function() {
  app.use(myOAP.auth());
  app.use(myOAP.login());
});
```

take a look at examples/simple.js. ensure you have at least the same middleware configured in your express app.
